name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './usa-location/package-lock.json'

    - name: Install dependencies
      run: npm ci
      working-directory: ./usa-location

    - name: Lint code
      run: npm run lint
      working-directory: ./usa-location

    - name: Build project
      run: npm run export
      working-directory: ./usa-location
      env:
        NODE_ENV: production

    - name: Add .nojekyll file
      run: touch ./usa-location/dist/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./usa-location/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
